services:
  postgres:
    image: postgres:16-alpine
    container_name: ventana_magica_db
    environment:
      POSTGRES_USER: dev_pnud
      POSTGRES_PASSWORD: M1d3sPnud@
      POSTGRES_DB: db_ventana_pnud
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
